// src/containers/ReferencesBanner/index.tsx
import React from "react";
import { ReferencesConfig, touch } from "../../shared";

export default function ReferencesBanner({
  pages,
}: Readonly<ReferencesConfig>): React.ReactElement {
  return (
    <div className="flex flex-col bg-gray-900 px-24 py-24">
      {pages
        .toSorted((a, b) => a.path.localeCompare(b.path))
        .map((page, i) => {
          const regexDetermineBeta =
            /(.+)?(\/content\/guxeu(?:-beta)?\/(?:.+)?)/gm;
          const linkBetaFix = page.path.replace(
            regexDetermineBeta,
            `$1/${touch}$2`,
          );
          return (
            <a
              key={i}
              href={linkBetaFix + ".html"}
              target="_blank"
              rel="noreferrer"
              className="font-medium text-cyan-500 hover:underline"
            >
              {page.path}
            </a>
          );
        })}
    </div>
  );
}

// src/lib/content/ReferencesBanner.svelte
<script lang="ts">
  import { regexDetermineBeta } from "$lib/storage";
  import type { HTMLAttributes } from "svelte/elements";

  type Props = App.ReferencesConfig & HTMLAttributes<EventTarget>;

  const { pages, ...restProps }: Props = $props();
</script>

<div {...restProps} class="referencesBanner">
  {#if pages.length !== 0}
    {#each pages.toSorted( ({ path }, { path: pathToCompare }) => path.localeCompare(pathToCompare) ) as { path } (path)}
      {@const href =
        path.replace(regexDetermineBeta, `$1/editor.html$2`) + ".html"}

      <a {href} target="_blank" rel="noreferrer">{path}</a>
    {/each}
  {:else}
    <p>No References Found</p>
  {/if}
</div>

<style lang="scss">
  div.referencesBanner {
    display: flex;
    flex-direction: column;
    background-color: slategray;
    padding: 96px;
    gap: 16px;

    a {
      width: fit-content;
      font-weight: 500;
      color: aqua;
      text-decoration-line: none;
      line-height: normal;

      &:hover {
        text-decoration-line: underline;
        color: aquamarine;
      }
    }
  }
</style>
